{% set name = "ace" %}
{% set version = "6.5.11" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-{{ version|replace(".", "_") }}/ACE-src-{{ version }}.tar.gz
    sha256: f935afecb0e39c734c8673d6a92c7d9d32bc5d224d315bd9410cbccc01351f1e
    patches:
      - prefix_perl.patch  # [unix]

build:
  number: 7

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - vs2017_win-64          # [win64]
    - make                   # [not win]
    - perl

test:
  commands:
    - test -f $PREFIX/lib/libACE.dylib  # [osx]
    - test -f $PREFIX/lib/libACE.so  # [linux]
    - if not exist %LIBRARY_LIB%\\ACE.lib exit 1  # [win]

about:
  home: https://www.dre.vanderbilt.edu/~schmidt/ACE.html
  license: DOC
  license_file: COPYING
  summary: 'The ADAPTIVE Communication Environment'
  description: 'The ADAPTIVE Communication Environment'
  dev_url: https://github.com/DOCGroup/ACE_TAO
  doc_url: https://www.dre.vanderbilt.edu/Doxygen/{{ version }}/html/
  license_url: https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/COPYING

extra:
  recipe-maintainers:
    - traversaro
    - jwillemsen
