{% set name = "ace" %}
{% set version = "8.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-{{ version|replace(".", "_") }}/ACE-src-{{ version }}.tar.gz
    sha256: 447e233c6a216e681f5124e74dcc918883d1d02eda1acb8537a462330d57b42e
    patches:
      - do_no_hardcode_cc_cxx_on_macos.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make                   # [not win]
    - perl

test:
  files:
    - ace_example.cpp

  requires:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

  commands:
    - test -f $PREFIX/lib/libACE.dylib  # [osx]
    - test -f $PREFIX/lib/libACE.so  # [linux]
    - if not exist %LIBRARY_LIB%\\ACE.lib exit 1  # [win]

about:
  home: https://www.dre.vanderbilt.edu/~schmidt/ACE.html
  license: DOC
  license_file: COPYING
  summary: The ADAPTIVE Communication Environment
  description: The ADAPTIVE Communication Environment
  dev_url: https://github.com/DOCGroup/ACE_TAO
  doc_url: https://www.dre.vanderbilt.edu/Doxygen/{{ version }}/html/
  license_url: https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/COPYING

extra:
  recipe-maintainers:
    - traversaro
    - jwillemsen
