bot:
  abi_migration_branches:
  - v6
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test: native_and_emulated
