conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
