conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
bot:
  abi_migration_branches:
  - v6
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
